// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20210720174901_parkStatusAndImg2")]
    partial class parkStatusAndImg2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AreaInSquareKm")
                        .HasColumnType("int");

                    b.Property<int>("Established")
                        .HasColumnType("int");

                    b.Property<string>("NearestTown")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkDescription")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkImg")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("ParkStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParkType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("VisitorCountInPreviousYear")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            AreaInSquareKm = 8983,
                            Established = 1872,
                            NearestTown = "West Yellowstone, Montana",
                            ParkDescription = "Yellowstone National Park is an American national park located in the western United States, largely in the northwest corner of Wyoming and extending into Montana and Idaho. It was established by the U.S. Congress and signed into law by President Ulysses S. Grant on March 1, 1872. Yellowstone was the first national park in the U.S. and is also widely held to be the first national park in the world. The park is known for its wildlife and its many geothermal features, especially Old Faithful geyser, one of its most popular. While it represents many types of biomes, the subalpine forest is the most abundant. It is part of the South Central Rockies forests ecoregion.",
                            ParkImg = "http://travelspot24.com/wp-content/uploads/2019/07/Yosemite-National-Park-Tours-Camping-Lodging-Weather-Location-Hotels-Restaurants-Travel-in-USA.jpg",
                            ParkName = "Yosemite",
                            ParkStatus = true,
                            ParkType = "National",
                            VisitorCountInPreviousYear = 3806306
                        },
                        new
                        {
                            ParkId = 2,
                            AreaInSquareKm = 2004,
                            Established = 1970,
                            NearestTown = "Anchorage, Alaska",
                            ParkDescription = "Chugach State Park covers 495,204 acres (2,004 square kilometers) immediately east of the Anchorage Bowl in south-central Alaska. Though primarily in the Municipality of Anchorage, a small portion of the park north of the Eklutna Lake area in the vicinity of Pioneer Peak lies within the Matanuska-Susitna Borough. Established by legislation signed into law on August 6, 1970, by Alaska Governor Keith Miller, this state park was created to provide recreational opportunities, protect the scenic value of the Chugach Mountains and other geographic features, and ensure the safety of the water supply for Anchorage. The park, managed by Alaska State Parks, is the third-largest state park in the United States, and consists of geographically disparate areas each with different attractions and facilities. Only Anza-Borrego Desert State Park in California and Wood-Tikchik State Park in western Alaska are larger. Hunting and fishing are permitted in the Chugach under regulations established by the Alaska Department of Fish and Game for game management unit 14c. Target practice is not allowed within the park boundaries.",
                            ParkImg = "https://cdn2.apstatic.com/photos/hike/7024748_medium_1554847576.jpg",
                            ParkName = "Chugach",
                            ParkStatus = true,
                            ParkType = "State",
                            VisitorCountInPreviousYear = 3806306
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
